name: AndrewMcGibbonBlog
favicon: null
layout_spectrum: 0.7562264211010188
typography_spectrum: 0.6713980515487492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4603598027024418
  lightness: 0.3028287445195019
  saturation: 0.6665433819871396
  rhythmicContrast: 0.6679677616339177
purpose: []
